package com.bdqn.bbh_zy.entity;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.room
     *
     * @mbggenerated
     */
    private Integer room;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.number
     *
     * @mbggenerated
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.size
     *
     * @mbggenerated
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.face
     *
     * @mbggenerated
     */
    private String face;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_room_room.square
     *
     * @mbggenerated
     */
    private Double square;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.id
     *
     * @return the value of bbh_room_room.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.id
     *
     * @param id the value for bbh_room_room.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.room
     *
     * @return the value of bbh_room_room.room
     *
     * @mbggenerated
     */
    public Integer getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.room
     *
     * @param room the value for bbh_room_room.room
     *
     * @mbggenerated
     */
    public void setRoom(Integer room) {
        this.room = room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.number
     *
     * @return the value of bbh_room_room.number
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.number
     *
     * @param number the value for bbh_room_room.number
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.size
     *
     * @return the value of bbh_room_room.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.size
     *
     * @param size the value for bbh_room_room.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.face
     *
     * @return the value of bbh_room_room.face
     *
     * @mbggenerated
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.face
     *
     * @param face the value for bbh_room_room.face
     *
     * @mbggenerated
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_room_room.square
     *
     * @return the value of bbh_room_room.square
     *
     * @mbggenerated
     */
    public Double getSquare() {
        return square;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_room_room.square
     *
     * @param square the value for bbh_room_room.square
     *
     * @mbggenerated
     */
    public void setSquare(Double square) {
        this.square = square;
    }
}