package com.bdqn.bbh_zy.entity;

import java.util.Date;

public class UserClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_class.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_class.classname
     *
     * @mbggenerated
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_class.teacher
     *
     * @mbggenerated
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbh_class.openinghours
     *
     * @mbggenerated
     */
    private Date openinghours;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_class.id
     *
     * @return the value of bbh_class.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_class.id
     *
     * @param id the value for bbh_class.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_class.classname
     *
     * @return the value of bbh_class.classname
     *
     * @mbggenerated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_class.classname
     *
     * @param classname the value for bbh_class.classname
     *
     * @mbggenerated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_class.teacher
     *
     * @return the value of bbh_class.teacher
     *
     * @mbggenerated
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_class.teacher
     *
     * @param teacher the value for bbh_class.teacher
     *
     * @mbggenerated
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbh_class.openinghours
     *
     * @return the value of bbh_class.openinghours
     *
     * @mbggenerated
     */
    public Date getOpeninghours() {
        return openinghours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbh_class.openinghours
     *
     * @param openinghours the value for bbh_class.openinghours
     *
     * @mbggenerated
     */
    public void setOpeninghours(Date openinghours) {
        this.openinghours = openinghours;
    }
}