package com.bdqn.bbh_zy.mapper;

import com.bdqn.bbh_zy.entity.Room;

public interface RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbh_room_room
     *
     * @mbggenerated
     */
    int insert(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbh_room_room
     *
     * @mbggenerated
     */
    int insertSelective(Room record);
}