package com.bdqn.bbh_zy.mapper;

import com.bdqn.bbh_zy.entity.UserClass;

public interface UserClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbh_class
     *
     * @mbggenerated
     */
    int insert(UserClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbh_class
     *
     * @mbggenerated
     */
    int insertSelective(UserClass record);
}