package com.example.demo.mapper;

import com.example.demo.entity.BbhClass;


import java.util.List;

public interface BbhClassMapper {
    /**
     * 查询
     * @param bbh
     * @return
     */
    List<BbhClass> bbhlist(BbhClass bbh);

    /**
     * 根据编号删除
     * @param id
     * @return
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 添加班级
     * @param bbh
     * @return
     */
    int insert(BbhClass bbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbh_class
     *
     * @mbggenerated
     */
    int insertSelective(BbhClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbh_class
     *
     * @mbggenerated
     */
    BbhClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbh_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BbhClass record);

    /**
     * 根据编号修改该班级信息
     * @param bbh
     * @return
     */
    int updateByPrimaryKey(BbhClass bbh);

    /**
     * 根据班级名查询
     * @param classname
     * @return
     */
    BbhClass selectByname(String classname);
}